### ISSUE TITLE
Wallet sync slows down after switching tabs within wallet. 

### ISSUE THREAD

**Issue by Menksy** [turtlecoin/turtlecoin-mobile-wallet#23] opened 2019-02-28 00:10 UTC
https://youtu.be/ezRXt-Rtd_A

**Comment by zpalmtree** [comment] 2019-02-28 01:29
Weird... There's only one thing that happens when you swap between tabs, and I don't understand how it could be interfering with this...

Logger might help diagnose, I can't reproduce myself.

**Comment by zpalmtree** [comment] 2019-02-28 05:09
I *think* this is fixed.

My best guess on what was happening is that when opening other tabs, it started their 'refresh'. In the example of the transactions screen, every second, it would grab all the transactions, and update the view. If you've got a lot of transactions, this could be pretty slow.

I made a number of optimizations which should make this no longer an issue. I'll leave this open though, as I'm not 100% it's fixed.

**Comment by zpalmtree** [comment] 2019-03-09 22:42
Closing for now, feel free to reopen if it still occurs with v0.0.5.

**Closed by zpalmtree** 2019-03-09 22:42 UTC
Labels: bug
