### ISSUE TITLE
Blocks lost during sync, possible malicious daemon

### ISSUE THREAD

**Issue by redispade** [turtlecoin/turtlecoin-mobile-wallet#57] opened 2019-03-19 18:36 UTC
![Uploading Screenshot_20190319-184451.png…]()

**Comment by redispade** [comment] 2019-03-19 18:37
![Screenshot_20190319-184451](https://user-images.githubusercontent.com/34771407/54632459-71609300-4a7e-11e9-8f0a-11fff79b3318.png)

**Comment by zpalmtree** [comment] 2019-03-19 18:42
Hiya,

Can you try closing the app and reopening it, and seeing if the issue persists?

**Comment by redispade** [comment] 2019-03-19 18:51
Tried multiple times, the app is stuck at block 1234254 but the blocks received are  1234255-1234275. It's stuck on that loop.

**Comment by zpalmtree** [comment] 2019-03-19 18:59
OK - I'll try and prepare a patch to fix this, not sure exactly what is causing it, but can at least keep the wallet syncing.

Meanwhile, you'll probably have to reimport via keys to start syncing again. I think I'll also add a 'Reset' button to help fix this.

**Comment by zpalmtree** [comment] 2019-03-19 18:59
Those blocks were quite a while ago, so shouldn't be related to a network fork...
:thinking:

**Comment by redispade** [comment] 2019-03-19 19:00
Is there a way to sync to a local lan daemon?

**Comment by zpalmtree** [comment] 2019-03-19 19:03
Not yet, it's planning to be added at some point. Not too hard to do, but this error actually occurs a lot more (this is the first time I've ever seen it with the cache) with a normal daemon, so I was hoping to handle that first before adding the option.

**Comment by zpalmtree** [comment] 2019-03-21 00:15
Resync option added, will see if I can fix the root cause now..

**Comment by zpalmtree** [comment] 2019-03-21 00:28
OK, patched so it won't get stuck in a loop anymore. Will be in the next release, which I'm probably going to make quite soon.

**Closed by zpalmtree** 2019-03-21 00:28 UTC
